# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios2020GroupProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

pod ‘SVProgressHUD’, ‘~> 2.2.5’
pod ‘SwiftLint’

  # Pods for ios2020GroupProject

end
